Add form to color picker
sipb/hydrant pull request #32
Opened 2023-03-04 02:24 UTC by fprasx

Also update button behaviour so that only manual section assignment or color assignment is toggled at once. Renaming and color assignment are deliberately left simultaneous in the case of a custom activity.

2023-03-04 05:51 UTC, cjquines commented
hm, we shd really get a formatter post commit or something

2023-03-04 19:11 UTC, psvenk requested changes
This looks great overall. I have a few comments.
- Clicking outside of the hex color input does not cause the color picker to update; only pressing Enter works. This leads to unintuitive UX if the user types a color and immediately clicks "Confirm".
- Is it possible to make the color input and reset/cancel/confirm buttons narrower (~ the previous width of the color preview and buttons)?
- Only inputs of the form `#abcdef` are accepted; it would be nice if `#abc` could be converted to `#aabbcc` and `#` could be added when not provided, and if entering an invalid input showed some sort of visual indication or at least causes the input to be consumed on enter/unfocus. (The canonicalization step can also regularize lowercase vs. uppercase; it seems that uppercase is preferred by the color picker.)
- Certain types of invalid inputs, like `#abcdek`, `#abcdefg`, and `#000000f`, cause unpredictable changes to the color depending on the previous state (in my testing, usually `#abcdef` or `#000000`).

2023-03-04 19:18 UTC, psvenk commented
Also, `ColorButton` is now dead code.

2023-03-05 18:31 UTC, fprasx commented
Concerns addressed. Shrinking the buttons is tough as they automatically fill the width of the container but making them shrink to their text content causes them to all have different sizes. Therefore, I shrunk the input form so the buttons expand to be smaller. 
![Screenshot 2023-03-05 at 1 31 16 PM](https://user-images.githubusercontent.com/91577249/222978968-72d0efde-bd4c-4309-8662-45542e3f3855.png)

2023-03-06 00:28 UTC, psvenk commented
Thanks for the changes. One more thing: what do you think of doing something like the following to make unfocus equivalent to submit?

```diff
diff --git a/src/components/ActivityButtons.tsx b/src/components/ActivityButtons.tsx
index 0a853b7..eb1e198 100644
--- a/src/components/ActivityButtons.tsx
+++ b/src/components/ActivityButtons.tsx
@@ -121,19 +121,22 @@ function ActivityColor(props: {

   const isError = input !== "" ? canonicalizeColor(input) === undefined : false;

+  const handleSubmit = (e: FormEvent) => {
+    e.preventDefault();
+    const canon = canonicalizeColor(input);
+    if (canon) {
+      setColor(canon);
+      setInput("");
+    }
+  }
+
   return (
     <Flex gap={2}>
       <HexColorPicker color={color} onChange={setColor} />
       <Flex direction="column" gap={2}>
         <form
-          onSubmit={(e) => {
-            e.preventDefault();
-            const canon = canonicalizeColor(input);
-            if (canon) {
-              setColor(canon);
-              setInput("");
-            }
-          }}
+          onSubmit={handleSubmit}
+          onBlur={handleSubmit}
         >
           <Input
             // Wide enough to hold everything, but keeps buttons below small
```

2023-03-06 01:08 UTC, fprasx commented
Seems good.

2023-03-06 01:22 UTC, psvenk approved these changes

2023-03-07 14:28 UTC, cjquines commented
@psvenk you know you can like. merge this

2023-03-08 05:54 UTC, merged