Migrate to Parcel
sipb/hydrant pull request #57
Opened 2023-09-26 21:30 UTC by 101arrowz

Apologies for the large change, but the majority of this diff is from the lockfile. I thought it would be a good idea to move off of Create React App since I need to refactor most of the build tooling anyway to make things work nicely with Node.js.

I understand if switching the build tooling entirely is too big a change to make, but we will need to sacrifice a lot of developer experience on the server-side code if we stay with CRA. This change makes hot reload on the frontend dramatically faster, and it obviously makes backend HMR much more doable.

I'll highlight the parts of this diff that actually should get review.

2023-09-26 21:31 UTC, 101arrowz commented on .env
> +API_BASE=https://hydrant.xvm.mit.edu
We probably need to use a separate xvm instance to do the server properly, unless we want to implement it all in CGI. @psvenk thoughts?

2023-09-26 21:32 UTC, 101arrowz commented on scripts/parcel-dev-reporter.js
> +const { fork } = require('child_process');
This is a small plugin to relaunch the server whenever you update the code. It's much more consistent than something like nodemon and not too hard to read.

2023-09-26 21:35 UTC, 101arrowz commented on src/components/ActivityDescription.tsx
> +        src={flagURLs[flag]}
We can get the old static links back if needed but this is the way Parcel suggests because it works better w.r.t. caching.

2023-09-26 21:53 UTC, 101arrowz commented on src-server/server.ts
> +for (const file in data) {
This is probably going to change to something more robust eventually. I was thinking of migrating all the scraping stuff into the Node.js backend so we'd have a single codebase for everything; does that seem reasonable?

2023-09-27 02:46 UTC, cjquines requested changes
i will as a matter of principle block this PR until more of how to develop is documented in the README.md, i think.

it doesn't have to be much, but enough that someone who doesn't care about the backend can spin up the frontend to work on it. the ideal would even be to explain how the backend works to someone who knows nothing about servers.

this is a big PR and can be split into several PRs:

* upgrading node to 18, which will need to touch the github workflows
* adding eslint, and fixing the codebase so there are no errors
  * (while we're at it, get prettier… the formatting in these files is inconsistent)
* importing the images rather than referring to them by url
* setting up a fastify server, setting it up to serve the files properly, setting up a deployment workflow, testing it, making sure it works, and documenting all this
  * (which can be done independently of ejecting from c-r-a! and probably should)
* moving the frontend to parcel

i don't actually care if it gets split up or not, i'll leave that to other maintainers. my major blocker is that this needs to be documented better. (my minor blocker is that we need to get prettier and make sure all our files end with newlines…)

2023-09-27 02:55 UTC, cjquines commented
also thanks for the work!!

2023-09-27 23:44 UTC, 101arrowz commented
Updated the docs a little but they're obviously not close to done. I'd like to be able to make the backend switch incrementally in a few separate PRs by the way; could you make a feature branch (`node-backend` or something) so I can PR to that without screwing up the main branch in the meanwhile? That should also make the incomplete docs less of an issue.

2023-09-27 23:53 UTC, 101arrowz commented
As you mentioned it would be a good idea to get Prettier set up and make the Fastify backend actually work in a separate PR, but I'd prefer to do that after this is merged to avoid merge conflicts.

Also, it's possible (but a pretty big pain) to undo some of the changes that aren't strictly related to Parcel (e.g. the beginnings of the backend) and redo them in a PR without ejecting CRA. I decided to do them in one go because the backend's development lifecycle actually depends on Parcel too, and doing them separately would've been pretty annoying, but I can still undo it if needed.

2023-09-28 02:01 UTC, 101arrowz commented
FYI I started [some work on the Fastify server](https://github.com/101arrowz/hydrant/pull/1/files#diff-2f7bba5c3aaddf413f1f0e764410ba7fdea9fb6e84ea11b8ede3034cfa16bf3d). Zod + Fastify is so much nicer to work with than Express!

2023-09-28 03:00 UTC, cjquines reviewed
unblocking, will leave someone else to approve

2023-09-28 03:01 UTC, cjquines approved these changes

2024-12-05 18:36 UTC, dtemkin1 commented
Hi! Is there any desire to rebase this PR on main? Migrating off of CRA would be really nice, but if not, I can open a new pull request

2025-03-02 03:29 UTC, gabrc52 commented
@dtemkin1 Is this PR still relevant?

It has been open for 2 years now

2025-03-02 19:24 UTC, dtemkin1 commented
Uhhh I think this PR was the start of making a backend for Hydrant, we should prob talk about it at today's meeting I suppose

2025-03-03 03:05 UTC, cjquines commented
this PR should be unnecessary now that we've moved to vite

2025-03-03 18:16 UTC, closed without merging

2025-03-03 21:52 UTC, cjquines commented
we should definitely use the fireroad backend instead when possible